### ISSUE TITLE
Feature Request: Remove ALL Borders

### ISSUE THREAD

**Issue by MagicOriole** [jshank/fvtt-rainbowroom#1]
Requesting a feature to go the opposite way, and remove all Borders. Thanks!

**Comment by jshank** [comment]
Does the [Clear Token Borders](https://github.com/jshank/fvtt-rainbowroo#main-interface) not achieve this? Or are you talking about token selection borders that are part of the core framework?

**Comment by jshank** [comment]
I'm going to close this for now since I'm not clear on what you're looking for. Feel free to comment or open another request with more information.
